url <- 'https://raw.githubusercontent.com/dssg-pt/covid19pt-data/master/data.csv'
last_n_days <- 30
source <- 'https://github.com/dssg-pt/covid19pt-data'
image_file <- 'image.png'
image_file2 <- 'image2.png'
line_color <- '#198ce7'
point_color <- '#198ce7'
text_color <- '#a0a0a3'
commit_message_file <- 'commit_message.txt'